# Generated by Django 3.1.4 on 2021-01-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='localtion',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='principle',
            new_name='principal',
        ),
    ]
